### ISSUE TITLE
Replace nodemon on production

### ISSUE THREAD

**Issue by noahsw** [league-wins-pool/league-wins-pool#10]
Nodemon is not meant to be run on production. We should explore using something like PM2 instead.

https://github.com/Unitech/pm2
https://doesnotscale.com/deploying-node-js-with-pm2-and-nginx/

**Comment by noahsw** [comment]
Nodemon is crashing in production

```bash
2015-04-28T10:27:22.615584125Z exception in nodemon killing node
2015-04-28T10:28:11.522762925Z Error: spawn ENOMEM
2015-04-28T10:28:11.522762925Z     at exports._errnoException (util.js:746:11)
2015-04-28T10:28:11.522762925Z     at ChildProcess.spawn (child_process.js:1162:11)
2015-04-28T10:28:11.522762925Z     at exports.spawn (child_process.js:995:9)
2015-04-28T10:28:11.522762925Z     at Object.exports.execFile (child_process.js:689:15)
2015-04-28T10:28:11.522762925Z     at exports.exec (child_process.js:649:18)
2015-04-28T10:28:11.522762925Z     at changeFunction (/usr/local/lib/node_modules/nodemon/lib/monitor/watch.js:93:7)
2015-04-28T10:28:11.522762925Z     at module.exports [as _onTimeout] (/usr/local/lib/node_modules/nodemon/lib/monitor/watch.js:289:5)
2015-04-28T10:28:11.522762925Z     at Timer.listOnTimeout (timers.js:110:15)
2015-04-28T10:28:27.925451674Z 
2015-04-28T10:28:27.925451674Z ----------------------------------------------------------
2015-04-28T10:28:27.925451674Z If appropriate, please file an error with the output from:
2015-04-28T10:28:27.925451674Z $ node /usr/local/bin/nodemon ./bin/www --dump
2015-04-28T10:28:27.925451674Z At http://github.com/remy/nodemon/issues/new
2015-04-28T10:28:27.925451674Z ----------------------------------------------------------
2015-04-28T10:28:27.925451674Z 
2015-04-28T10:28:27.925451674Z 
2015-04-28T10:28:27.925451674Z npm ERR! Linux 3.13.0-43-generic
2015-04-28T10:28:27.925451674Z npm ERR! argv "node" "/usr/local/bin/npm" "start"
2015-04-28T10:28:27.925451674Z npm ERR! node v0.12.2
2015-04-28T10:28:27.925451674Z npm ERR! npm  v2.7.3
2015-04-28T10:28:27.925451674Z npm ERR! code ELIFECYCLE
2015-04-28T10:28:27.925451674Z npm ERR! server@0.0.1 start: `NODE_ENV=production nodemon ./bin/www`
2015-04-28T10:28:27.925451674Z npm ERR! Exit status 1
2015-04-28T10:28:27.925451674Z npm ERR! 
2015-04-28T10:28:27.925451674Z npm ERR! Failed at the server@0.0.1 start script 'NODE_ENV=production nodemon ./bin/www'.
2015-04-28T10:28:27.925451674Z npm ERR! This is most likely a problem with the server package,
2015-04-28T10:28:27.925451674Z npm ERR! not with npm itself.
2015-04-28T10:28:27.925451674Z npm ERR! Tell the author that this fails on your system:
2015-04-28T10:28:27.925451674Z npm ERR!     NODE_ENV=production nodemon ./bin/www
2015-04-28T10:28:27.925451674Z npm ERR! You can get their info via:
2015-04-28T10:28:27.925451674Z npm ERR!     npm owner ls server
2015-04-28T10:28:27.925451674Z npm ERR! There is likely additional logging output above.
2015-04-28T10:28:27.925451674Z 
2015-04-28T10:28:27.925451674Z npm ERR! Please include the following file with any support request:
2015-04-28T10:28:27.925451674Z npm ERR!     /webapp/server/npm-debug.log
```


http://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn
